### ISSUE TITLE
Can embark DApps run on other ETH wallets?

### ISSUE THREAD

**Issue by php-wizard** [status-im/embark-status#10]
Hi,
i intend to make DApps with embark, because AFAIK it's the only ETH framework that provides a messaging system so far, and i need it.
A few questions:

- if my DApp uses Whisper for messagging, will it be able to run only on the Status browser, or also Mist , Parity, Brave, etc. when they will have Whisper implemented?
- is there any cost per message sent? Any limitations?
- can Status directly resolve Swarm URLs, or will do that ?

Thanks

**Comment by jrainville** [comment]
Hi @sleepndevelop , sorry for the late reply, most of the team was on vacation for the holidays,
Also, you might have gotten a faster reply by posting in the main Embark repo here https://github.com/embark-framework/embark as this the repo for the embark-status plugin.

As for your questions:
- While using Embark, any platform that supports Whisper will work
- There is no cost to send or receive anything. No big limitation comes to mind
- For swarm URLs, I'm not sure what you mean. Do you mean when going in Status' Dapp explorer, enterning the Swarm URL will redirect to the Dapp?

Thanks for your interest, hope this answers most of your questions

**Comment by php-wizard** [comment]
@jrainville  About Swarm, yes, but also for any files that the DApp may use , like CSS/JS files.

Currently, ETH wallets only support SWARM via local HTTP proxy , i.e. you have to add http://localhost:8500/bzz:/ at the beginning of the url, not just bzz:// 

That may be a problem if the user has the local proxy disabled. 
Or also if a DApp creator has bought a  .eth domain, he may want it to be accessible via a nice URL like
bzz://my-dapp-domain.eth without localhost proxy.

This has been discussed in a medium article about DApp development, but i can't find it anymore

**Comment by jrainville** [comment]
Ah ok. I don't know. Embark doesn't do that, but I can't answer for Status itself as I don't develop on the App itself.
