### ISSUE TITLE
DApp doesn't add to Status

### ISSUE THREAD

**Issue by coyotespike** [status-im/embark-status#2]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: `embark run` does not add `embark_demo` to Status contacts

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
After `embark simulator` and `embark run`, Embark app should appear in Status DApp contacts.
#### Actual behavior
[comment]: # (Describe what actually happened.)
App can be reached through Console `/browse http://10.0.3.2:8000` but does not appear in list of contacts.
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

`/debug On`
```
adb reverse tcp:8081 tcp:8081
adb reverse tcp:3449 tcp:3449
adb forward tcp:5561 tcp:5561
```
`embark simulator`
`embark run`

### Additional Information

* Operating System: Android

**Comment by coyotespike** [comment]
With `adb reverse tcp:8000 tcp:8000`, the DApp can be reached through console `/browse http://localhost:8000` but does not appear in list of contacts. Also does not show up in `re-frisk` list of contacts.

**Comment by emizzle** [comment]
Hi @coyotespike, I believe this issue is now quite outdated. Is this still an issue for you?
