### ISSUE TITLE
DApp does not show current state of smart contract

### ISSUE THREAD

**Issue by coyotespike** [status-im/embark-status#3]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: the `embark_demo` default page returns blank value for state of smart contract

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
After `/browse` to the correct URL and clicking on `Get Value , the DApp page should show the smart contract has an initial value of 100.
#### Actual behavior
[comment]: # (Describe what actually happened.)
The initial value returns blank.
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

`/debug On`
```
adb reverse tcp:8081 tcp:8081
adb reverse tcp:3449 tcp:3449
adb forward tcp:5561 tcp:5561
```
`embark simulator`
`embark run`

Browse to appropriate URL.
Zoom in. Click "Get Value."
`Click the button to get the current value. The initial value is `

### Additional Information

* Operating System: Android

**Comment by emizzle** [comment]
Hi @coyotespike, I believe this issue is now quite outdated. Is this still an issue for you?
